name: proyecto_tec
description: A new Flutter project.
publish_to: 'none'
version: 1.1.16

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.1

  path_provider: ^2.0.8

  file_picker: ^8.0.7

  collection: ^1.15.0
  flutter_blue: ^0.8.0
  flutter_blue_plus: ^1.31.13
  flutter_reactive_ble: ^5.3.0
  syncfusion_flutter_gauges: ^26.2.9
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/AttaBotLogo.png
    - assets/AttaBotRobot_uno.png
    - assets/AttaBotRoboInicio.png

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Italic.ttf
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-ExtraBold.ttf
          style: italic

